name: ci

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        experimental: [false]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo test --no-run --workspace --no-fail-fast --all-features
      - name: test (default features)
        run: cargo test --workspace --no-fail-fast
      - name: test (all features)
        run: cargo test --workspace --no-fail-fast --all-features
      - name: test (no default features)
        run: cargo test --workspace --no-fail-fast --no-default-features
