name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: install trunk, wasm-bindgen-cli
        run: cargo binstall --no-confirm trunk wasm-bindgen-cli
      - name: build
        run: trunk build --release
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./package/gui/dist
          cname: secalc.gohla.nl
